# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0emessages.proto\">\n\x0eSkipperCommand\x12\x14\n\x0csailPosition\x18\x01 \x01(\x05\x12\x16\n\x0erudderPosition\x18\x02 \x01(\x11\"\x1f\n\x0bSailCommand\x12\x10\n\x08position\x18\x01 \x01(\x05\"!\n\rRudderCommand\x12\x10\n\x08position\x18\x01 \x01(\x11\"\x14\n\x04Mode\x12\x0c\n\x04mode\x18\x01 \x01(\x05\"\x92\x01\n\nBaseToBoat\x12\"\n\x07skipper\x18\x01 \x01(\x0b\x32\x0f.SkipperCommandH\x00\x12\x1c\n\x04sail\x18\x02 \x01(\x0b\x32\x0c.SailCommandH\x00\x12 \n\x06rudder\x18\x03 \x01(\x0b\x32\x0e.RudderCommandH\x00\x12\x15\n\x04mode\x18\x05 \x01(\x0b\x32\x05.ModeH\x00\x42\t\n\x07\x63ommand\":\n\nSailStatus\x12\x14\n\x0csailPosition\x18\x01 \x01(\x05\x12\x16\n\x0erudderPosition\x18\x02 \x01(\x11\"%\n\x0bPowerStatus\x12\x16\n\x0e\x62\x61tteryVoltage\x18\x01 \x01(\x05\"T\n\nBoatToBase\x12\x1c\n\x05sails\x18\x01 \x01(\x0b\x32\x0b.SailStatusH\x00\x12\x1d\n\x05power\x18\x02 \x01(\x0b\x32\x0c.PowerStatusH\x00\x42\t\n\x07\x63ommandb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SKIPPERCOMMAND = _descriptor.Descriptor(
  name='SkipperCommand',
  full_name='SkipperCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sailPosition', full_name='SkipperCommand.sailPosition', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rudderPosition', full_name='SkipperCommand.rudderPosition', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=80,
)


_SAILCOMMAND = _descriptor.Descriptor(
  name='SailCommand',
  full_name='SailCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='SailCommand.position', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=113,
)


_RUDDERCOMMAND = _descriptor.Descriptor(
  name='RudderCommand',
  full_name='RudderCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='RudderCommand.position', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=148,
)


_MODE = _descriptor.Descriptor(
  name='Mode',
  full_name='Mode',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mode', full_name='Mode.mode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=170,
)


_BASETOBOAT = _descriptor.Descriptor(
  name='BaseToBoat',
  full_name='BaseToBoat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skipper', full_name='BaseToBoat.skipper', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sail', full_name='BaseToBoat.sail', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rudder', full_name='BaseToBoat.rudder', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mode', full_name='BaseToBoat.mode', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command', full_name='BaseToBoat.command',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=173,
  serialized_end=319,
)


_SAILSTATUS = _descriptor.Descriptor(
  name='SailStatus',
  full_name='SailStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sailPosition', full_name='SailStatus.sailPosition', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rudderPosition', full_name='SailStatus.rudderPosition', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=379,
)


_POWERSTATUS = _descriptor.Descriptor(
  name='PowerStatus',
  full_name='PowerStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='batteryVoltage', full_name='PowerStatus.batteryVoltage', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=418,
)


_BOATTOBASE = _descriptor.Descriptor(
  name='BoatToBase',
  full_name='BoatToBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sails', full_name='BoatToBase.sails', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power', full_name='BoatToBase.power', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='command', full_name='BoatToBase.command',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=420,
  serialized_end=504,
)

_BASETOBOAT.fields_by_name['skipper'].message_type = _SKIPPERCOMMAND
_BASETOBOAT.fields_by_name['sail'].message_type = _SAILCOMMAND
_BASETOBOAT.fields_by_name['rudder'].message_type = _RUDDERCOMMAND
_BASETOBOAT.fields_by_name['mode'].message_type = _MODE
_BASETOBOAT.oneofs_by_name['command'].fields.append(
  _BASETOBOAT.fields_by_name['skipper'])
_BASETOBOAT.fields_by_name['skipper'].containing_oneof = _BASETOBOAT.oneofs_by_name['command']
_BASETOBOAT.oneofs_by_name['command'].fields.append(
  _BASETOBOAT.fields_by_name['sail'])
_BASETOBOAT.fields_by_name['sail'].containing_oneof = _BASETOBOAT.oneofs_by_name['command']
_BASETOBOAT.oneofs_by_name['command'].fields.append(
  _BASETOBOAT.fields_by_name['rudder'])
_BASETOBOAT.fields_by_name['rudder'].containing_oneof = _BASETOBOAT.oneofs_by_name['command']
_BASETOBOAT.oneofs_by_name['command'].fields.append(
  _BASETOBOAT.fields_by_name['mode'])
_BASETOBOAT.fields_by_name['mode'].containing_oneof = _BASETOBOAT.oneofs_by_name['command']
_BOATTOBASE.fields_by_name['sails'].message_type = _SAILSTATUS
_BOATTOBASE.fields_by_name['power'].message_type = _POWERSTATUS
_BOATTOBASE.oneofs_by_name['command'].fields.append(
  _BOATTOBASE.fields_by_name['sails'])
_BOATTOBASE.fields_by_name['sails'].containing_oneof = _BOATTOBASE.oneofs_by_name['command']
_BOATTOBASE.oneofs_by_name['command'].fields.append(
  _BOATTOBASE.fields_by_name['power'])
_BOATTOBASE.fields_by_name['power'].containing_oneof = _BOATTOBASE.oneofs_by_name['command']
DESCRIPTOR.message_types_by_name['SkipperCommand'] = _SKIPPERCOMMAND
DESCRIPTOR.message_types_by_name['SailCommand'] = _SAILCOMMAND
DESCRIPTOR.message_types_by_name['RudderCommand'] = _RUDDERCOMMAND
DESCRIPTOR.message_types_by_name['Mode'] = _MODE
DESCRIPTOR.message_types_by_name['BaseToBoat'] = _BASETOBOAT
DESCRIPTOR.message_types_by_name['SailStatus'] = _SAILSTATUS
DESCRIPTOR.message_types_by_name['PowerStatus'] = _POWERSTATUS
DESCRIPTOR.message_types_by_name['BoatToBase'] = _BOATTOBASE

SkipperCommand = _reflection.GeneratedProtocolMessageType('SkipperCommand', (_message.Message,), dict(
  DESCRIPTOR = _SKIPPERCOMMAND,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:SkipperCommand)
  ))
_sym_db.RegisterMessage(SkipperCommand)

SailCommand = _reflection.GeneratedProtocolMessageType('SailCommand', (_message.Message,), dict(
  DESCRIPTOR = _SAILCOMMAND,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:SailCommand)
  ))
_sym_db.RegisterMessage(SailCommand)

RudderCommand = _reflection.GeneratedProtocolMessageType('RudderCommand', (_message.Message,), dict(
  DESCRIPTOR = _RUDDERCOMMAND,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:RudderCommand)
  ))
_sym_db.RegisterMessage(RudderCommand)

Mode = _reflection.GeneratedProtocolMessageType('Mode', (_message.Message,), dict(
  DESCRIPTOR = _MODE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:Mode)
  ))
_sym_db.RegisterMessage(Mode)

BaseToBoat = _reflection.GeneratedProtocolMessageType('BaseToBoat', (_message.Message,), dict(
  DESCRIPTOR = _BASETOBOAT,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:BaseToBoat)
  ))
_sym_db.RegisterMessage(BaseToBoat)

SailStatus = _reflection.GeneratedProtocolMessageType('SailStatus', (_message.Message,), dict(
  DESCRIPTOR = _SAILSTATUS,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:SailStatus)
  ))
_sym_db.RegisterMessage(SailStatus)

PowerStatus = _reflection.GeneratedProtocolMessageType('PowerStatus', (_message.Message,), dict(
  DESCRIPTOR = _POWERSTATUS,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:PowerStatus)
  ))
_sym_db.RegisterMessage(PowerStatus)

BoatToBase = _reflection.GeneratedProtocolMessageType('BoatToBase', (_message.Message,), dict(
  DESCRIPTOR = _BOATTOBASE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:BoatToBase)
  ))
_sym_db.RegisterMessage(BoatToBase)


# @@protoc_insertion_point(module_scope)
